exchange: binance
timeframe: 5m
symbols:
- COIN50
strategy:
  ema_fast: 20
  ema_slow: 50
  rsi_period: 14
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9
  obv_lookback: 20
  psar_step: 0.02
  psar_max: 0.2
  atr_period: 14
  atr_mult: 2.0
  use_pullback_entry: true
  rsi_long_min: 50
  rsi_short_max: 50
  obv_slope_min: 0.0
  use_psar: true
risk:
  initial_equity: 10000
  allocation_per_trade_cash: 1000
  max_positions: 10
  fee_rate: 0.0004
  slippage: 0.0002
backtest:
  from_days_ago: 120
forward:
  poll_seconds: 15
