COIN50 = [
    "BTC/USDT","ETH/USDT","BNB/USDT","SOL/USDT","XRP/USDT","ADA/USDT","DOGE/USDT","TON/USDT","TRX/USDT","SHIB/USDT",
    "AVAX/USDT","DOT/USDT","LINK/USDT","MATIC/USDT","LTC/USDT","UNI/USDT","BCH/USDT","ATOM/USDT","ETC/USDT","XLM/USDT",
    "IMX/USDT","APT/USDT","NEAR/USDT","FIL/USDT","LDO/USDT","ARB/USDT","AAVE/USDT","SUI/USDT","OP/USDT","HBAR/USDT",
    "RUNE/USDT","ALGO/USDT","INJ/USDT","VET/USDT","MKR/USDT","QNT/USDT","MANA/USDT","AXS/USDT","SAND/USDT","EGLD/USDT",
    "THETA/USDT","FLOW/USDT","XTZ/USDT","APE/USDT","KAS/USDT","SNX/USDT","GRT/USDT","SEI/USDT","ARKM/USDT","PEPE/USDT"
]