COIN50 = [
    "BTC/USDT","ETH/USDT","BNB/USDT","SOL/USDT","XRP/USDT","ADA/USDT","AVAX/USDT",
    "DOGE/USDT","TRX/USDT","DOT/USDT","LINK/USDT","MATIC/USDT","ATOM/USDT","LTC/USDT",
    "UNI/USDT","ICP/USDT","ETC/USDT","XMR/USDT","FIL/USDT","NEAR/USDT","APT/USDT",
    "ARB/USDT","AAVE/USDT","OP/USDT","VET/USDT","EGLD/USDT","HBAR/USDT","RNDR/USDT",
    "GRT/USDT","FTM/USDT","INJ/USDT","SAND/USDT","THETA/USDT","MANA/USDT","RUNE/USDT",
    "QNT/USDT","FLOW/USDT","STX/USDT","IMX/USDT","AXS/USDT","CRV/USDT",
    "1INCH/USDT","DYDX/USDT","MINA/USDT","ENS/USDT","KAVA/USDT","SNX/USDT","ZEC/USDT",
    "GMX/USDT","PEPE/USDT"
]
